version: '3.8'
services:
  db:
    container_name: sreality-scraper-db
    image: postgres:13.4
    restart: on-failure
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=devdb
    ports:
      - "5432:5432"
    networks:
      - internal
  scraper:
    container_name: sreality-scraper
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_SERVER=db
    depends_on:
      - db
    restart: on-failure
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    networks:
      - internal

networks:
  internal:
